version: "3.9"

services:
  database:
    image: postgres
    container_name: api-database
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: 'redis:alpine'
    container_name: api-redis
    ports:
      - 6379:6379
    networks:
      - webnet

  app_dev:
    container_name: api
    restart: always
    build:
      context: .
      target: development
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webnet
    links: 
      - database
      - redis
    depends_on:
      - database
      - redis
    
networks:
  webnet:
    
volumes:
  pgdata: